version: '3.8'

services:
  neo4j-api-test-neo4j:
    image: neo4j:4.2@sha256:44ae8c7bb6d605bea1f34c0f2457f45a1120b9054b3e501d942686d21e597061
    ports:
      - published: $NEO4J_TEST_NEO4J_HTTP_PORT
        target: 7474
      - published: $NEO4J_TEST_NEO4J_BOLT_PORT
        target: 7687
    environment:
      NEO4J_AUTH: none
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
